version: '3.8'

services:
  anki-vocab:
    build:
      context: .
      dockerfile: Dockerfile
    image: anki-ai-vocab:latest
    container_name: anki-vocab
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - ANKI_HOST=host.docker.internal
      - ANKI_PORT=${ANKI_PORT:-8765}
      - DECK_NAME=${DECK_NAME:-English Vocabulary}
      - MODEL_NAME=${MODEL_NAME:-Basic}
    volumes:
      - ./config:/home/vocabuser/.config/anki-vocab
    # For macOS/Windows users (default):
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # For Linux users, comment out extra_hosts above and uncomment below:
    # network_mode: "host"
    stdin_open: true
    tty: true